import { createBPHandlers } from './bp';
import { createExchangeHandler } from './exchange';
import { I_MatchHandlers, MatchMode } from './types';

export const matchFlowMap: Record<MatchMode, I_MatchHandlers<any>> = {
    [MatchMode.normal]: createBPHandlers('預設BP流程', [
        { option: 'ban', amount: 1, teamIndex: 0 },
        { option: 'ban', amount: 1, teamIndex: 1 },
        { option: 'ban', amount: 1, teamIndex: 0 },
        { option: 'ban', amount: 1, teamIndex: 1 },
        { option: 'ban', amount: 1, teamIndex: 0 },
        { option: 'ban', amount: 1, teamIndex: 1 },
        { option: 'pick', amount: 1, teamIndex: 0 },
        { option: 'pick', amount: 2, teamIndex: 1 },
        { option: 'pick', amount: 2, teamIndex: 0 },
        { option: 'pick', amount: 2, teamIndex: 1 },
        { option: 'pick', amount: 2, teamIndex: 0 },
        { option: 'pick', amount: 2, teamIndex: 1 },
        { option: 'pick', amount: 1, teamIndex: 0 },
        { option: 'ban', amount: 1, teamIndex: 1 },
        { option: 'ban', amount: 1, teamIndex: 0 },
        { option: 'ban', amount: 1, teamIndex: 1 },
        { option: 'ban', amount: 1, teamIndex: 0 },
        { option: 'pick', amount: 1, teamIndex: 1 },
        { option: 'pick', amount: 2, teamIndex: 0 },
        { option: 'pick', amount: 2, teamIndex: 1 },
        { option: 'pick', amount: 2, teamIndex: 0 },
        { option: 'pick', amount: 2, teamIndex: 1 },
        { option: 'pick', amount: 2, teamIndex: 0 },
        { option: 'pick', amount: 1, teamIndex: 1 },
    ]),
    [MatchMode.test]: createBPHandlers('測試用簡短BP流程', [
        { option: 'ban', amount: 1, teamIndex: 0 },
        { option: 'ban', amount: 1, teamIndex: 1 },
        { option: 'pick', amount: 1, teamIndex: 0 },
        { option: 'pick', amount: 2, teamIndex: 1 },
        { option: 'pick', amount: 2, teamIndex: 0 },
        { option: 'pick', amount: 1, teamIndex: 1 },
    ]),
    [MatchMode.exchange]: createExchangeHandler('含交換制BP流程', [
        { option: 'ban', amount: 1, teamIndex: 0 },
        { option: 'ban', amount: 1, teamIndex: 1 },
        { option: 'ban', amount: 1, teamIndex: 0 },
        { option: 'ban', amount: 1, teamIndex: 1 },
        { option: 'ban', amount: 1, teamIndex: 0 },
        { option: 'ban', amount: 1, teamIndex: 1 },
        { option: 'pick', amount: 1, teamIndex: 0 },
        { option: 'pick', amount: 2, teamIndex: 1 },
        { option: 'pick', amount: 2, teamIndex: 0 },
        { option: 'pick', amount: 2, teamIndex: 1 },
        { option: 'pick', amount: 2, teamIndex: 0 },
        { option: 'pick', amount: 2, teamIndex: 1 },
        { option: 'pick', amount: 1, teamIndex: 0 },
        { option: 'ban', amount: 1, teamIndex: 1 },
        { option: 'ban', amount: 1, teamIndex: 0 },
        { option: 'ban', amount: 1, teamIndex: 1 },
        { option: 'ban', amount: 1, teamIndex: 0 },
        { option: 'pick', amount: 1, teamIndex: 1 },
        { option: 'pick', amount: 2, teamIndex: 0 },
        { option: 'pick', amount: 2, teamIndex: 1 },
        { option: 'pick', amount: 2, teamIndex: 0 },
        { option: 'pick', amount: 2, teamIndex: 1 },
        { option: 'pick', amount: 2, teamIndex: 0 },
        { option: 'pick', amount: 2, teamIndex: 1 },
        { option: 'pick', amount: 1, teamIndex: 0 },
        { option: 'exchange', amount: 1 },
    ]),
    [MatchMode.testExchange]: createExchangeHandler('測試用含交換制簡短BP流程', [
        { option: 'ban', amount: 1, teamIndex: 0 },
        { option: 'ban', amount: 1, teamIndex: 1 },
        { option: 'pick', amount: 1, teamIndex: 0 },
        { option: 'pick', amount: 1, teamIndex: 1 },
        { option: 'exchange', amount: 1 },
        { option: 'pick', amount: 1, teamIndex: 1 },
        { option: 'pick', amount: 1, teamIndex: 0 },
    ]),
};
